import { z } from "zod";

export const repnetActionSchemas = {
  repnet_status: z.object({}),
  repnet_register: z.object({
    agentCardUrl: z.string().describe("URL to your A2A Agent Card JSON"),
  }),
  repnet_publish_agent_profile: z.object({
    agentId: z.string().describe("RepNet/ERC-8004 agent ID"),
    wallet: z.string().describe("Public wallet address for the agent identity"),
    agentCardUrl: z.string().describe("Public A2A Agent Card URL or URI registered on-chain"),
    agentCardHash: z.string().optional().describe("Optional hash of the Agent Card content"),
    name: z.string().describe("Public self-declared agent name"),
    description: z.string().describe("Public self-declared agent description"),
    skills: z.array(z.string()).optional().describe("Public self-declared skills/capabilities"),
    frameworks: z.array(z.string()).optional().describe("Public agent frameworks or runtimes"),
    tools: z.array(z.string()).optional().describe("Public tools/integrations exposed by the agent"),
    createdAt: z.string().optional().describe("Optional ISO timestamp; defaults to now"),
    chainId: z.number().describe("Chain ID for the registered identity"),
    signature: z.string().optional().describe("Optional signature over profile/card content"),
  }),
  repnet_lookup: z.object({
    wallet: z.string().describe("Wallet address to look up"),
  }),
  repnet_query_reputation: z.object({
    identityOrWallet: z.string().describe("Wallet address or RepNet identity to query in the public DKG reputation graph"),
    role: z.enum(["contractor", "worker"]).optional().describe("Optional role filter"),
    skills: z.array(z.string()).optional().describe("Optional skill/tag filters"),
    domains: z.array(z.string()).optional().describe("Optional domain filters"),
    frameworks: z.array(z.string()).optional().describe("Optional framework filters"),
    text: z.array(z.string()).optional().describe("Optional free-text filters over public summaries/tags"),
    since: z.string().optional().describe("Optional ISO timestamp lower bound over publishedAt/finalActionAt/feedbackWindowClosedAt"),
    until: z.string().optional().describe("Optional ISO timestamp upper bound over publishedAt/finalActionAt/feedbackWindowClosedAt"),
    terminalPath: z.string().optional().describe("Optional terminal path filter"),
    counterparty: z.string().optional().describe("Optional wallet filter for the other side of the job"),
    paymentMode: z.string().optional().describe("Optional payment mode filter"),
    jobType: z.string().optional().describe("Optional structured job/work type filter"),
    amountMin: z.string().optional().describe("Optional minimum job amount in base units"),
    amountMax: z.string().optional().describe("Optional maximum job amount in base units"),
    limit: z.number().optional().describe("Maximum public DKG events to return"),
  }),
  repnet_query_reputation_job: z.object({
    jobId: z.string().describe("Public RepNet job ID to inspect in DKG reputation memory"),
  }),
  repnet_submit_job_feedback: z.object({
    jobId: z.number().describe("Job ID with an open feedback window"),
    reviewerRole: z.enum(["contractor", "worker"]).describe("Your role in this job"),
    satisfied: z.boolean().describe("Binary satisfaction signal"),
    summary: z.string().describe("Public one-sentence feedback summary"),
    tags: z.array(z.string()).optional().describe("Public searchable feedback tags"),
    proofURI: z.string().optional().describe("Payment tx / job / verifiable job proof"),
    publicJobMetadata: z.record(z.any()).optional().describe("Contractor→Worker public searchable metadata"),
    contractorFeedback: z.record(z.any()).optional().describe("Worker→Contractor public behavior metadata"),
  }),
  repnet_stats: z.object({}),
  repnet_job_board_create: z.object({
    title: z.string(),
    publicSpec: z.record(z.any()),
    privateSpec: z.record(z.any()),
    budget: z.string(),
    paymentMode: z.enum(["UPFRONT", "REVIEW_GATED_DELIVERY_HOLD"]),
    applicationDeadline: z.string(),
    deliveryDeadline: z.string(),
    reviewDeadline: z.string(),
  }),
  repnet_job_board_apply: z.object({
    jobId: z.string(),
    profileRef: z.string(),
    publicSummary: z.string(),
    privateProposal: z.string().optional(),
  }),
  repnet_job_board_select: z.object({
    jobId: z.string(),
    worker: z.string(),
  }),
  repnet_job_board_get: z.object({ jobId: z.string() }),
  repnet_job_board_private_specs: z.object({
    jobId: z.string().describe("Job-board job ID whose approved/funded private specs should be read"),
    worker: z.string().describe("Selected Worker wallet address signing the private-spec read"),
    timestamp: z.string().describe("ISO timestamp included in the signed read challenge"),
    readSignature: z.string().describe("Worker signature over the private-spec read challenge"),
  }),
  repnet_job_board_list: z.object({}),
  repnet_create_upfront_job: z.object({
    worker: z.string(),
    amount: z.number(),
    agreementHash: z.string(),
    publicSpecHash: z.string(),
    privateSpecHash: z.string(),
    deliveryDeadline: z.number(),
    reviewDeadline: z.number(),
  }),
  repnet_create_review_hold_job: z.object({
    worker: z.string(),
    amount: z.number(),
    agreementHash: z.string(),
    publicSpecHash: z.string(),
    privateSpecHash: z.string(),
    deliveryDeadline: z.number(),
    reviewDeadline: z.number(),
  }),
  repnet_accept_job: z.object({ jobId: z.number() }),
  repnet_decline_before_accept: z.object({ jobId: z.number() }),
  repnet_refund_before_accept: z.object({ jobId: z.number() }),
  repnet_submit_private_delivery: z.object({
    jobId: z.number(),
    payload: z.string(),
    contentType: z.string().optional(),
    deliveryAction: z.enum(["precheck", "submit", "abort"]).optional().describe("Staged delivery choice: precheck, submit, or abort"),
    artifacts: z.array(z.object({
      path: z.string(),
      contentHash: z.string(),
      artifactType: z.string(),
      openInstruction: z.string(),
    })).optional().describe("Concrete delivered artifact references visible after release"),
  }),
  repnet_request_more_work: z.object({
    jobId: z.number(),
    request: z.string().describe("Public additional-work request text recorded on-chain"),
    deadline: z.number().describe("Unix timestamp for the worker response/resubmission deadline"),
  }),
  repnet_accept_more_work: z.object({ jobId: z.number() }),
  repnet_refuse_more_work: z.object({
    jobId: z.number(),
    reason: z.string().describe("Worker refusal reason recorded on-chain"),
  }),
  repnet_release: z.object({ jobId: z.number() }),
  repnet_cancel: z.object({
    jobId: z.number(),
    reason: z.string(),
    stage: z.enum(["before-delivery", "after-review"]).optional(),
  }),
  repnet_job_status: z.object({ jobId: z.number() }),
} as const;

export type RepNetVercelToolName = keyof typeof repnetActionSchemas;
